<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3download"
 *
 * Auto generated by Extension Builder 2014-01-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Download files',
	'description' => 'A minimal service TYPO3 extension that allows downloading one or more files from the webserver\'s local file system',
	'category' => 'services',
	'author' => 'Tomita Militaru, Pascal Alich',
	'author_email' => 'mail@tomitamilitaru.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>